### ISSUE TITLE
SQL Server insert into identity column fails due to case insensitivity

### ISSUE THREAD

**Issue by NeonRodman** [sranka/jdbcimage#21]
when importing data from a MSSQL schema that has an IDENTITY column to a schema that also has the same IDENTITY column, the check for whether this is true is case sensitive and fails.

We have debugged this and added 1 line shown below as a fix. We will make a pull request asap.

    private boolean importsToIdentityColumns(TableInfo tableInfo, ResultSetInfo fileInfo) {
        Set<String> identityColumns = tableIdentityColumns.get(tableInfo.getTableName());
        if (identityColumns != null) {
            Set<String> schemaColumns = tableInfo.getTableColumns().keySet();
            Set<String> importedColumns = Arrays.stream(fileInfo.columns)
                    .filter(col -> schemaColumns.contains(col.toLowerCase()))
                    .map(String::toLowerCase); // this line fixes it
                    .collect(Collectors.toSet());
            return identityColumns.stream().anyMatch(importedColumns::contains);
        }
        return false;
    }

**Comment by sranka** [comment]
fixed by #22 , available in [0.9.1](https://github.com/sranka/jdbcimage/releases/tag/v0.9.1)
